### ISSUE TITLE
IR Ring Testing 

### ISSUE THREAD

**Issue by marialramosc** [RoBorregos/robocup-soccer-light-2024#6]
Test the IR Ring, check if its sending signal to the arduino

**Comment by marialramosc** [comment]
IR Ring tested, its not sending signal to arduino. Waiting on electronics to re-connect the Ring

**Comment by GustavoHR842** [comment]
The IR Ring is re-connected.

**Comment by GustavoHR842** [comment]
Some tests were done and IR Ring is working.

**Comment by marialramosc** [comment]
IR Ring Testing with code that gives angle and strength. Code is already committed. Angles that the ring detects are in a different orientation that the actual angles of the robot (like shown in the image below). Tomorrow (2 april) the IR Ring will be rotated so the angles detected and the real angles are coherent. This will be done with electronics help.   

![IMG_2797](https://github.com/RoBorregos/robocup-soccer-light-2024/assets/78754174/9df71795-8fe7-4b01-bda1-7886e96eed60)
